### ISSUE TITLE
how can i set some server options like docment root?

### ISSUE THREAD

**Issue by l396635210** [insidestyles/swoole-bridge-bundle#5]
swoole document:  

```
$server->set([
    'document_root' => '/data/webroot/example.com', // v4.4.0以下版本, 此处必须为绝对路径
    'enable_static_handler' => true,
]);

```

[https://wiki.swoole.com/#/http_server?id=document_root](https://wiki.swoole.com/#/http_server?id=document_root)

**Comment by insidestyles** [comment]
you can extend SwooleBridgeServerCommand and set up your defined options

**Comment by l396635210** [comment]
thanks~
